### ISSUE TITLE
Trouble creating new logbook

### ISSUE THREAD

**Issue by partofthething** [ctjacobs/pyqso#20]
I just cloned this repo and am running it for the first time. When I choose Open or Create I was given an open dialog but had no option to create a new SQL database from scratch so I was unable to make my first logbook. Am I missing something?

**Comment by ctjacobs** [comment]
This unfortunately has been an issue for other users too. I'll work on a better solution for this. For now, in the Open dialog, you'll need to click on the pencil icon in the top left-hand side (highlighted red in the image below). A text box will be displayed where you can enter the desired location and name of the file (highlighted blue). Clicking the Open button will then create the logbook file if it doesn't already exist.

![pyqso_open](https://cloud.githubusercontent.com/assets/5470627/6077775/3355b782-adea-11e4-9470-19450c5da4f1.png)

Alternatively, you can specify the desired path and name of the logbook file using

```
pyqso --logbook /path/to/my/new_logbook.db
```

If `new_logbook.db` doesn't exist, then it will be created for you.

**Comment by partofthething** [comment]
Got it. Thanks. Maybe separate  `New` and `Open` menu entries would make it more clear.

**Comment by ctjacobs** [comment]
No problem - thanks for raising the issue. I'll leave this open until I address it in a future release.

**Comment by ctjacobs** [comment]
Addressed by e6e8570 in `master`. Closing.
