### ISSUE TITLE
List of valid modes is out of date

### ISSUE THREAD

**Issue by ctjacobs** [ctjacobs/pyqso#24]
The `MODES` list in `adif.py` needs to be updated.

**Comment by dnet** [comment]
Check out my branch `adif-modes` at https://github.com/dnet/pyqso/tree/adif-modes and merge if you were thinking about something like this or reply in a comment if not. I found the `--color-words` parameter of `git diff` and `git show` to be useful to display differences in a way that's easier to understand in situations like this. I sorted the list alphabetically, that caused some elements to be moved around, so if you think something important got removed, check first if it's there in the "right" place (according to this new sort order).

**Comment by dnet** [comment]
I used this as a reference http://www.adif.org/304/ADIF_304.htm#Mode_Enumeration

**Comment by ctjacobs** [comment]
Thanks for taking a look at this. Strictly speaking the 'modes' like CHIP64 and CHIP128 should be part of a new `SUBMODES` ADIF field, while CHIP should be specified in the existing `MODES` ADIF field.

Perhaps PyQSO could have `CHIP` (i.e. no submode), `CHIP:CHIP64`, and `CHIP:CHIP128` in the combo box of the Records dialog (i.e. `self.sources["MODE"]`). Then when `RecordDialog`'s `__init__` and `get_data` are called, split up the string and assign to `MODE` and `SUBMODE`, e.g.:

```
diff --git a/pyqso/record_dialog.py b/pyqso/record_dialog.py
index 42785ce..1677019 100644
--- a/pyqso/record_dialog.py
+++ b/pyqso/record_dialog.py
@@ -430,7 +430,19 @@ class RecordDialog(Gtk.Dialog):
       if(field_name == "CALL"):
          # Always show the callsigns in upper case.
          return self.sources[field_name].get_text().upper()
-      elif(field_name == "BAND" or field_name == "MODE" or field_name == "QSL_SENT" or field_name == "QSL_RCVD"):
+      elif(field_name == "SUBMODE"):
+         s = self.sources["MODE"].get_active_text()
+         s = s.split(":")
+         # Get the submode. If no submode is specified, return an empty string.
+         try:
+            return s[1]
+         except IndexError:
+            return ""
+      elif(field_name == "MODE"):
+         s = self.sources["MODE"].get_active_text()
+         s = s.split(":")
+         return s[0]
+      elif(field_name == "BAND" or field_name == "QSL_SENT" or field_name == "QSL_RCVD"):
          return self.sources[field_name].get_active_text()
       elif(field_name == "NOTES"):
          (start, end) = self.sources[field_name].get_bounds()
```

**Comment by ctjacobs** [comment]
A new Submode field has now been created - see the `submodes` branch. This also contains some fixes following the move to Python 3. Just need to make sure that deprecated `MODE` values are dealt with correctly.

**Comment by ctjacobs** [comment]
I think this has now been fixed in `master`.
