### ISSUE TITLE
Callsign map

### ISSUE THREAD

**Issue by ctjacobs** [ctjacobs/pyqso#26]
Add the option of showing where a given station is in the world. Need to handle the special case where a callsign is being used in a different country, e.g. PA/MYCALL.

**Comment by dnet** [comment]
Where would this be invoked from? In the toolbox? Where would the callsign come from?

**Comment by ctjacobs** [comment]
Initially I was thinking of having another button next to the "Callsign" entry box in the Add/Edit Record dialog. When clicked, another dialog opens up to show a map of the world with the country highlighted somehow. But I think this will just clutter things. Perhaps just a one-line label containing the country's name under the entry box would be better - it auto-appears when the country has been determined based on the Callsign data.

**Comment by Rotzke** [comment]
+1

**Comment by Rotzke** [comment]
What about greyline map? Like, showing the connection between QTH and currently selected in the logbook callsign. Would be cool to visualize.

**Comment by ctjacobs** [comment]
Good idea. However, I'd rather do this using the COUNTRY or GRID_LOCATOR fields instead of the CALL (callsign) field. These fields are potentially more accurate station locators, and this option removes the need to maintain (or hard-code a link to) a list of callsign prefixes and their corresponding countries.

**Comment by Rotzke** [comment]
COUNTRY in such case. Grid locators aren't written each time, plus we have no auto fill of this field in PyQSO, although the country is 99% caught on QRZ.com or manually.

**Comment by ctjacobs** [comment]
Agreed - COUNTRY it is.

**Comment by ctjacobs** [comment]
Branch `callsign-map` set up for this. If a QSO is clicked on, it gets the latitude-longitude coordinates of the COUNTRY using geocoding. However, depending on the speed of the internet connection / server response time, this can degrade performance as the QSO isn't actually selected until `on_selection_changed` is finished - I wonder if there's a way of doing a non-blocking lookup. Still need to plot the QTH on the grey line map which will likely require some refactoring of the `draw` method.

**Comment by ctjacobs** [comment]
I'm going to design a right-click popup menu for lookup purposes. This will also allow help a copy/paste feature to be implemented in the future (see #57).

**Comment by ctjacobs** [comment]
Popup menu added along with basic functionality for plotting station locations on the grey line map. Needs testing and a few small improvements, but feel free to checkout the `callsign-map` and use in the mean time.

**Comment by ctjacobs** [comment]
Basic functionality documented and tested. Now merged into `master`.
