### ISSUE TITLE
[dxcluster] It's not possible to see every return value

### ISSUE THREAD

**Issue by r4mp** [ctjacobs/pyqso#45]
If I connect e.g. to dxfun.com:8000 via telnet and type 'help' I get this

> HELP El comando HELP (AYUDA)
>  HELP existe para un cierto n�mero de comandos. La sintaxis es:
> 
>   HELP <cmd>
> 
>  Donde <cmd> es el nombre del comando de cual quieres ayuda.
> 
>  Todos los comandos pueden ser abreviados, SHOW/DX puede ser
>  abreviado con SH/DX, ANNOUNCE puede acortarse en AN, etc.
> 
>  Busca con el comando APROPOS <cadena> que chequea el fichero
>  completo de ayuda por la <cadena> que especifiques y te dar
>  una lista de comandos que luego podr�s mirar con HELP.

In PyQSO I get no response. It seems to be a problem with multi line responses, because I can see 'normal' notifications like 'pls set your qth' etc.

**Comment by ctjacobs** [comment]
Addressed by commit ce46c1409637d6fd6884a2b1519a06aacda267e3. A few characters weren't being decoded successfully (specially, those characters which have been replaced by question marks "�" in your telnet example), which caused an exception. I haven't found a robust way of handling such characters, so for now they are replaced with a replacement marker (like the one used in your telnet example). Please try again with the latest version of the `master` branch.
