### ISSUE TITLE
Window implementation via glade

### ISSUE THREAD

**Issue by r4mp** [ctjacobs/pyqso#47]
Maybe it's a good idea to seperate gui and program logic via glade files.

> try:  
>     from gi.repository import Gtk  
> except:  
>     print("GTK Not Available")  
>     sys.exit(1)                                                                                                                                                                               
> 
> APPDIR = os.path.dirname(os.path.abspath(**file**))                                                                                                                                           
> 
> class MyWindow(Gtk.Window):                                                                                                                                                                   
> 
> ```
> def __init__(self):                                                                                                                                                                       
>     self.builder = Gtk.Builder()                                                                                                                                                          
>     self.builder.add_from_file("assets/ui/main.glade")                                                                                                                                 
>     self.window = self.builder.get_object("windowMain")
> ```
> 
> ...

**Comment by ctjacobs** [comment]
Good suggestion. I've started working on this in the `glade` branch.

**Comment by ctjacobs** [comment]
Addressed by pull request #54.
