### ISSUE TITLE
Backport python2 , for use hamlib

### ISSUE THREAD

**Issue by gaionim** [ctjacobs/pyqso#50]
For using hamlib  I must run python2,
Seems only some lib import and name change.
See attach, seems to work for me.
Warning !!! little tested 

[patch.zip](https://github.com/ctjacobs/pyqso/files/485736/patch.zip)

**Comment by ctjacobs** [comment]
Thanks for the patch. After reading [some documentation on porting](https://docs.python.org/3/howto/pyporting.html), I think this is fine. I've changed the `except` blocks to `except ImportError`.
