### ISSUE TITLE
Missing requirements file

### ISSUE THREAD

**Issue by AlmightyOatmeal** [ctjacobs/pyqso#63]
The project is missing a Python dependancies file: `requirements.txt` so when I run it, I run into dependency hell as I install each missing dependency by hand.

**Comment by ctjacobs** [comment]
I've now added a `requirements.txt` file and updated the steps in the README - Hopefully this will help. Unfortunately not all of the packages are available through PyPI so the `requirements.txt` is not a complete dependencies list.
